apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: {{ .Values.auth.image }}
          ports:
            - containerPort: {{ .Values.auth.port }}
          env:
            - name: MONGO_URL
              value: "mongodb://mongo:27017/tondb"
            - name: REDIS_URL
              value: "redis://redis:6379"
            - name: RABBITMQ_URL
              value: "amqp://user:password@rabbitmq:5672"