{{- range .Values.mongoMicroservices }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-{{ .name }}-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
{{- end }}