{{- range .Values.microservices }}
{{- if .mongoPort }}
apiVersion: v1
kind: Service
metadata:
  name: mongo-{{ .name }}
spec:
  selector:
    app: mongo-{{ .name }}
  ports:
    - name: mongo
      protocol: TCP
      port: {{ .mongoPort }}
      targetPort: {{ $.Values.mongo.port }}
---
{{- end }}
{{- end }}