apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.containerName }}
spec:
  selector:
    app: {{ .Values.containerName }}
  ports:
{{- range $index, $port := .Values.service.ports }}
    - name: port-{{ $index }}
      port: {{ $port.host }}
      targetPort: {{ $port.container }}
      protocol: TCP
{{- end }}
  type: ClusterIP
