apiVersion: v1
kind: Secret
metadata:
  name: rabbitmq-secret
type: Opaque
data:
  rabbitmq-user: {{ .Values.rabbitmq.user | b64enc | quote }}
  rabbitmq-password: {{ .Values.rabbitmq.password | b64enc | quote }}